[sw_licenses] Class takes similar arg as RosPack. This enables LicenseUtil to cooperate with RosPack, which is used internally.
[sw_licenses] Small refactoring; Remove unnecessary return value.

[sw_licenses] Add tests.

- Adding another test pkg, in order to preserve what's been used as it is.
  - For some reason the dependency isn't captured on Travis CI, so the license record file only contains the pkg itself.
- To the new test pkg, add "qt4-qmake" as a depend, as its license let me find locally an issue in license comparison feature.

[sw_licenses] Trying to fix import error in a test. Not sure why but this change fixed the following error.

https://travis-ci.org/ros-infrastructure/rospkg/jobs/397073625
```
======================================================================
ERROR: test.test_rospkg_sw_licenses.test_compare_license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.6/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
      self.test(*self.arg)
        File "/home/travis/build/ros-infrastructure/rospkg/test/test_rospkg_sw_licenses.py", line 42, in test_compare_license
    manager = rospkg.sw_license.LicenseUtil(ros_paths=[search_path])
    AttributeError: 'module' object has no attribute 'sw_license'
```

[sw_licenses] Improve exception.

[S/W license] Debug var names. Better err msgs.